### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by xionglingfeng** [akesterson/dpath-python#39] opened 2015-08-30 06:17 UTC
It seems `dpath.util.merge` cannot handle dictionaries with unicode keys. For example,

```
a = {'中': ['zhong']}
b = {'文': ['wen']}
dpath.util.merge(a, b)
```

The above code will fail with

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\uXXXX' in position 0
: ordinal not in range(128)
```

**Comment by akesterson** [comment] 2015-09-12 21:14
Thanks for the bug report. I'll look into this as soon as possible.

**Comment by akesterson** [comment] 2015-09-16 05:13
After some looking, i'm not convinced that this is actually a bug. Take a look at the new tests/test_unicode.py file on master, and the results of Travis test https://travis-ci.org/akesterson/dpath-python/builds/80571775 ... None of the python configurations tested (2.6 up to 3.4 and pyp) failed the test.

Can you provide some more information about your environment?

* python version
* dpath version
* operating system version
* system locale variable, if possible
* a complete, self-contained failure case executed from the interactive interpreter, under the above conditions (the above code looks like a failure case, but I can't make it fail, so please copy/paste a complete failure scenario from an interactive python interpreter).

Thanks, I'll be happy to continue looking into this when I have more information to go off of.

**Comment by xhh2a** [comment] 2015-09-16 16:27
I had it fail for me too

**Comment by akesterson** [comment] 2015-09-19 05:20
xhh2a, thanks for the failure confirmation. str() and an ascii-encoded separator are most likely what's biting us here. Since I can't reproduce this on my side (even though my $LANG is en_US.UTF-8 also on ubuntu 14.04 w/ 2.7.6 and dpath 1.4.0), can someone tell me if the following things make a difference:

* Enforce unicode separators (force it via unicode(separator), for example)
* replace str(v) with unicode(repr(v))

The str(v) bit is there to cover the case of building string paths over integer indexes in lists. We could also get around this by more verbosely checking if (v) is an integer, and then repr()'ing it, and otherwise leaving already subclass(basestring) keys alone.

I'm open to suggestions, and am pretty frustrated I can't reproduce this on my side.

**Comment by xhh2a** [comment] 2015-09-19 06:49
I'll test this sometime when I'm not busy fixing things at work (working right now on debugging stuff for work). Python's unicode implementation is unfortunately very hit and miss on 2.X.

**Comment by xhh2a** [comment] 2015-09-23 21:29
```
>>> b = { u'语' : 'asdadsa' }}
>>> a = { u'正体字': 'n' }' }
>>> dpath.util.merge(a, b, separator=u'/')
...
    _check_typesafe(dst, src, v, separator.join([_path, str(v)]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u8bed' in position 0: ordinal not in range(128)
```
Will test the second part in a bit

**Comment by xhh2a** [comment] 2015-09-24 00:59
I fixed the separator thing and the path join but it still crashes. I think it's because the dictionary object is a utf encoded str.
```python
from __future__ import unicode_literals  # Can we do this? How far back in python are we trying to support?
def try_encode(obj):
    try:
        return obj.decode('utf-8')
    except Exception:
        return obj

def merge(dst, src, separator="/", afilter=None, flags=MERGE_ADDITIVE, _path=""):
    separator = try_encode(separator)
    _path = try_encode(_path)
    _check_typesafe(dst, src, v, separator.join([_path, try_encode(v)]))
```

**Comment by xhh2a** [comment] 2015-09-24 01:15
See issue #41 for code that works in python 2.7 (fails the tests so I assume it doesn't work in python 3

**Comment by xhh2a** [comment] 2015-09-24 17:53
On another note, I'm not sure if dpath necessarily needs a merge function. I personally use underscore.py's _.extend()
https://github.com/serkanyersen/underscore.py

**Comment by akesterson** [comment] 2015-10-11 16:11
FYI, this is waiting on pull request #41 . Thanks for being patient while we discuss implementation details, OP.

**Comment by calebcase** [comment] 2020-01-26 20:24
All done and fixed in 2.x. Thanks for the report!

**Closed by calebcase** 2020-01-26 20:24 UTC
Labels: 1.0, bug
